### PR TITLE
add music sample

### PR DESCRIPTION
**Pull request by rsxdalv**
generated using https://github.com/rsxdalv/tts-generation-webui

### CODE REVIEW

**Comment by JohnTesla** [comment]
Please tall me, M-GEN and A-GEN can use small checkpoint models? (small-med-large music audio) instead of HUGE (many GB!) diffusers in HF/Hub

**Comment by JohnTesla** [comment]
Can you help me? Why TTS-generation-webui-with RVC Beta inside can work gradio==3.35.2  
   but Retrieval_based_Voice_Conversion_WebUI ....  cannot work gradio>=3.34.0 how to run it with gradio 3.35?

**Comment by rsxdalv** [comment]
My flight arrives in about 18 hours, I can investigate after that.

**Comment by rsxdalv** [comment]
> Can you help me? Why TTS-generation-webui-with RVC Beta inside can work gradio==3.35.2 but Retrieval_based_Voice_Conversion_WebUI .... cannot work gradio>=3.34.0 how to run it with gradio 3.35?

I remember that I always did some work for adapting the other projects (here - RVC) but it might have been quite, maybe as easy as just installing the newer gradio version. In your case, I'd recommend opening an issue on the RVC project and maybe tagging me there since my project uses RVC with 3.35.2 gradio.

**Comment by rsxdalv** [comment]
> Please tall me, M-GEN and A-GEN can use small checkpoint models? (small-med-large music audio) instead of HUGE (many GB!) diffusers in HF/Hub

The models are multiple gigabytes. I cannot tell you the exact reason why it _has to be like that_, just that audio models are _surprisingly_ large and slow, unlike one might expect given the other AI models.

**Comment by JohnTesla** [comment]
> > Can you help me? Why TTS-generation-webui-with RVC Beta inside can work gradio==3.35.2 but Retrieval_based_Voice_Conversion_WebUI .... cannot work gradio>=3.34.0 how to run it with gradio 3.35?
> 
> I remember that I always did some work for adapting the other projects (here - RVC) but it might have been quite, maybe as easy as just installing the newer gradio version. In your case, I'd recommend opening an issue on the RVC project and maybe tagging me there since my project uses RVC with 3.35.2 gradio.

Thanks! My idea was: to integrate Full RVC inside the TTS-GEN, Because I wanna train RVC also in TTS-GEN Webui.
So RVC full cannot use the same ENV form TTS because of Gradio Ver, so Just need to use a new ENV with gradio 34 for run RVCfull in separated UI

**Comment by rsxdalv** [comment]
I like your idea. Please create this issue in the tts project

**Comment by JohnTesla** [comment]
Please tell some more Man. If I want to TTS using trained RVC model (pth+index) how can I do this directly, avoid of generating some speech then transfer to RVC gen

**Comment by rsxdalv** [comment]
Was planning for that, but you can make a feature request for it in the
main repo.

For background - before I went on a holiday I was busy with migratong away
from gradio, which I need to build more complex pipelines and better UX;
now, I'm still returning.

**Pull request merged**
